Param()

# Walk commits in chronological order and create semver tags when a bump occurs
$version = [int[]](0,0,0)

function Bump-Major { $script:version[0]++; $script:version[1]=0; $script:version[2]=0 }
function Bump-Minor { $script:version[1]++; $script:version[2]=0 }
function Bump-Patch { $script:version[2]++ }

Write-Host "Scanning commits to determine tag points..."
$commits = git rev-list --reverse --pretty=format:%H master | Where-Object { $_ -match '^[0-9a-f]{40}$' }

foreach ($sha in $commits)
{
    $msg = git log -n 1 --pretty=format:%s $sha
    $lower = $msg.ToLower()

    $bumped = $false
    if ($msg -match '!|BREAKING') { Bump-Major; $bumped = $true }
    elseif ($lower -match '\bfeat\b' -or $lower -match '\bfeature\b') { Bump-Minor; $bumped = $true }
    elseif ($lower -match '\bfix\b' -or $lower -match '\bbug\b') { Bump-Patch; $bumped = $true }

    if ($bumped)
    {
        $tag = "v$($version[0]).$($version[1]).$($version[2])"
        Write-Host "Tagging $sha -> $tag ($msg)"
        git tag -a $tag $sha -m "Release $tag - generated by history rewrite"
    }
}

Write-Host "Done. Tags created locally. Review before pushing."
